### ISSUE TITLE
error when trying to cnnect to matic mainnet

### ISSUE THREAD

**Issue by hshar7** [maticnetwork/eth-dagger.js#43]
```
(node:21) UnhandledPromiseRejectionWarning: Error: Connection closed
    at /app/node_modules/mqtt/lib/client.js:124:29
    at Array.forEach (<anonymous>)
    at flushVolatile (/app/node_modules/mqtt/lib/client.js:122:24)
    at Duplex.<anonymous> (/app/node_modules/mqtt/lib/client.js:358:5)
    at Duplex.emit (events.js:315:20)
    at emitClose (/app/node_modules/ws/lib/stream.js:12:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise r
ejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

eth mainnet is working fine

**Comment by vrustik** [comment]
Is there any way to connect matic mainnet?

**Comment by senilshah** [comment]
I am facing similar issue, Do we need to change something in ('matic-mainnet.dagger.matic.network') url or is there any alternative way to complete it?

**Comment by jarrodlilkendey** [comment]
i'm facing this same issue. has anyone found a solution?

**Comment by hshar7** [comment]
Dagger is being deprecated, better to call web3js directly with an rpc endpoint from maticvigil

**Comment by arnold-almeida** [comment]
Thanks for the info @hshar7 

May be worth putting a deprecation notice in the README and updating the website.

**Comment by 0fatih** [comment]
@hshar7  do you know is there a web socket provider for matic?

**Comment by cryptowalletr** [comment]
> i'm facing this same issue. has anyone found a solution?

Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.

**Comment by cryptowalletr** [comment]
> I am facing similar issue, Do we need to change something in ('matic-mainnet.dagger.matic.network') url or is there any alternative way to complete it?

Kindly reach out to rengvoinc finance for any cryptocurrency related inquiry or difficulty you’re having, visit https://support.rengvoinc.com/welcome-to-rengvoinc-wallet-support/ get swift response and help on how to solve the issue and any other related problem you are having.
